version: '3'
services:
  taas-es-processor:
    image: taas-es-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    ports:
      - 3001:3001
